name: bulletr
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # --- 核心依赖 (App运行时必须的) ---
  # 状态管理 (我们教程用的是这个)
  provider: ^6.1.1 
  # 日期格式化
  intl: ^0.19.0
  # 生成唯一ID
  uuid: ^4.3.3
  # 谷歌字体 (你之前加了，保留它)
  google_fonts: ^6.3.3
  # 图标
  cupertino_icons: ^1.0.8

  flutter_slidable: ^3.1.0

  url_launcher: ^6.2.1
  
  # 注意：我暂时移除了 isar 和 flutter_riverpod
  # 因为我们第一阶段用 Provider + 内存存储，避免库冲突和代码混淆。
  # 等你熟悉了，我们再加回数据库。

dev_dependencies:
  flutter_test:
    sdk: flutter
  # 代码规范检查
  flutter_lints: ^3.0.0

  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon" # 安卓图标的文件名
  ios: true                # 如果以后做iOS，这也顺便生成了
  image_path: "assets/icon/icon.png" # 你的图标路径
  min_sdk_android: 21      # 最小兼容版本
  # 如果你想让图标在安卓上自动适应圆形/圆角（自适应图标），可以去掉下面这行的注释并设置背景色
  # adaptive_icon_background: "#FFFFFF"